# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Cache Setup
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --use-pep517 .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m pip install flake8
          flake8 . --count --show-source --statistics

      - name: Lint with isort
        run: |
          python -m pip install isort
          isort -c python/

      - name: Lint with black
        run: |
          python -m pip install black
          black --check python/
          black --check tests/

      - name: Test with pytest
        run: |
          python -m pip install pytest
          pytest
